/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:9b155082-3e81-4f74-a88c-a62406950082",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_qgBTV6cjO",
    "aws_user_pools_web_client_id": "7g73q7mcm2tl6315ch824k1vhs",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://kysbsilwdnftrlup6f2ilkddwa.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
